apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: tap-on-tkg
  namespace: tanzulab
spec:
  topology:
    controlPlane:
      replicas: 3
      vmClass: best-effort-large
      storageClass: ds
      volumes: 
        - name: etcd
          mountPath: /etc/lib/etcd
          capacity:
            storage: 16Gi
      tkr:  
        reference:
          name: v1.24.9---vmware.1-tkg.4
    nodePools:
    - name: tap-on-tkg-pool-1
      replicas: 6
      vmClass: best-effort-large
      storageClass: ds
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 64Gi
      tkr:  
        reference:
          name: v1.24.9---vmware.1-tkg.4
  settings:
    storage:
      defaultClass: ds
    network:
      cni:
        name: antrea
      trust: 
        additionalTrustedCAs:
          - name: tap-on-tkg-ca
            data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU0VENDQThtZ0F3SUJBZ0lVVTBMaitSVWJwYUw2RC9Wd1kwYXlqTmNSNFk0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dab3hDekFKQmdOVkJBWVRBbE5ITVF3d0NnWURWUVFJREFOVFIxQXhFakFRQmdOVkJBY01DVk5wYm1kaApjRzl5WlRFUE1BMEdBMVVFQ2d3R1ZrMTNZWEpsTVE0d0RBWURWUVFMREFWVVlXNTZkVEVpTUNBR0ExVUVBd3daClZrMTNZWEpsSUZOMFpYWmxiaUJGWVhONUxWSlRRU0JEUVRFa01DSUdDU3FHU0liM0RRRUpBUllWZUdsdWMzUmwKZG1WdWJFQjJiWGRoY21VdVkyOXRNQjRYRFRJek1ETXlOakU1TkRNd04xb1hEVE16TURNeU16RTVORE13TjFvdwpnWm94Q3pBSkJnTlZCQVlUQWxOSE1Rd3dDZ1lEVlFRSURBTlRSMUF4RWpBUUJnTlZCQWNNQ1ZOcGJtZGhjRzl5ClpURVBNQTBHQTFVRUNnd0dWazEzWVhKbE1RNHdEQVlEVlFRTERBVlVZVzU2ZFRFaU1DQUdBMVVFQXd3WlZrMTMKWVhKbElGTjBaWFpsYmlCRllYTjVMVkpUUVNCRFFURWtNQ0lHQ1NxR1NJYjNEUUVKQVJZVmVHbHVjM1JsZG1WdQpiRUIyYlhkaGNtVXVZMjl0TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF3b2lXCms5STFDTk5yRHQxVDVDUzFNamI4bWF6V3lCbDVSS1M1Ri8raUpya0U1Q0tHMDY0QVdUVWI2ZHA3QmtjZXU5N2EKR3VmN3NEbjd6TUtVNGRrblo3TlltcDU5bFhaMklMZjJlZ3RZUWhsQ0RIRE4zakdvRERNTjZiV2h2ZDRlUzkyWQpCdlNtK1MyUVUzVEZqWXdIaGI3cFBOSEMxaDRSeittVFdzcXVTQmRxSko5U3FEMHZXT3JSQkJlRWlBaWZMMmtOCkJMMGgzUzhFMTdxSCtsSlJjS1h1MTlHekNRb1lseHdPdXdwMFVDTXhreWJvd1VHVEtweWwwK3RDTmNhb01Eby8KNW1jUG1qSVBFdHU5L1NFTHZBZ0IrR2JodGtUdy9xUFVNSDgybm5rY0hQTTZPMEJuYVFOOWUvdFRsV2ptMzNLNApFbnF1aEhrN2NINUZ4YTNoZHdJREFRQUJvNElCR3pDQ0FSY3dEQVlEVlIwVEJBVXdBd0VCL3pBZEJnTlZIUTRFCkZnUVVhOGg4R2w1VmNoTW1KcjBGajRCSVJFK1pHdmt3Z2RvR0ExVWRJd1NCMGpDQno0QVVhOGg4R2w1VmNoTW0KSnIwRmo0QklSRStaR3ZtaGdhQ2tnWjB3Z1pveEN6QUpCZ05WQkFZVEFsTkhNUXd3Q2dZRFZRUUlEQU5UUjFBeApFakFRQmdOVkJBY01DVk5wYm1kaGNHOXlaVEVQTUEwR0ExVUVDZ3dHVmsxM1lYSmxNUTR3REFZRFZRUUxEQVZVCllXNTZkVEVpTUNBR0ExVUVBd3daVmsxM1lYSmxJRk4wWlhabGJpQkZZWE41TFZKVFFTQkRRVEVrTUNJR0NTcUcKU0liM0RRRUpBUllWZUdsdWMzUmxkbVZ1YkVCMmJYZGhjbVV1WTI5dGdoUlRRdVA1RlJ1bG92b1A5WEJqUnJLTQoxeEhoampBTEJnTlZIUThFQkFNQ0FRWXdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBSUpXcjFDajBYc3drMUdkCnEvQzBWMDIvcUlGLzdqOHV6TlBjL085Zi9VNGNuRHl4NW1wRXpVU25YR2N2YWxHME1WRnVBSU9DekFZcjd6RnoKN3ZoQjN1TiszbUsvNnRSZUhlbjdHSFBZcTMxWFlWcnNidGlBR0xzbmN5bXpJOCtmU2RYS1JOajhUVzlTUDBiSApNNEZzK3hnU3BTNGFRUzZLL2xiNUx4Z1hEbTI4MndOL1RaTGwrOC82TDA0dkFZdWo1ZHMzbUhsSHRMMGRFTWhKCkxzM1pGc0ZxYXZzVVNlQU0yMnovZlY4dXNGQkVSb00vZnNrczd2dmZ0N2dXb24vSUhuVEtPWDVMNCtySWwzc1oKZDJya2ZZOEpBT25LOEtlcldGMkszeVc0dDROUXZhblh0dGpXOWdlbTZ0NmNmODFuTTJEcjFjcWN0RWJFeDBHRApzdFM3Nys0PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
