apiVersion: run.tanzu.vmware.com/v1alpha2
kind: TanzuKubernetesCluster
metadata:
  name: vlp-cls-1
  namespace: tanzulab
spec:
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-large
      storageClass: ds
      volumes: 
        - name: etcd
          mountPath: /etc/lib/etcd
          capacity:
            storage: 16Gi
      tkr:  
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
    nodePools:
    - name: vlp-cls-1-pool
      replicas: 3
      vmClass: best-effort-large
      storageClass: ds
      volumes:
        - name: containerd
          mountPath: /var/lib/containerd
          capacity:
            storage: 64Gi
      tkr:  
        reference:
          name: v1.22.9---vmware.1-tkg.1.cc71bc8
  settings:
    storage:
      defaultClass: ds
    network:
      cni:
        name: antrea
      trust: 
        additionalTrustedCAs:
          - name: vmware-tanzu-vlp-ca
            data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUhGekNDQlArZ0F3SUJBZ0lVQng0UU5pZTdrQWh1WW5YVWdBaUIrVDBTRmp3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2dhd3hDekFKQmdOVkJBWVRBbE5ITVJJd0VBWURWUVFJREFsVGFXNW5ZWEJ2Y21VeEVqQVFCZ05WQkFjTQpDVk5wYm1kaGNHOXlaVEVoTUI4R0ExVUVDZ3dZVmsxM1lYSmxJRk5wYm1kaGNHOXlaU0JNZEdRZ1VIUmxNUTR3CkRBWURWUVFMREFWdFlYQmlkVEVjTUJvR0ExVUVBd3dUVmsxWFlYSmxJRlJoYm5wMUlGWk1VQ0JEUVRFa01DSUcKQ1NxR1NJYjNEUUVKQVJZVmVHbHVjM1JsZG1WdWJFQjJiWGRoY21VdVkyOXRNQjRYRFRJeU1EZ3hOREEzTWpBeApNRm9YRFRNeU1EZ3hNVEEzTWpBeE1Gb3dnYXd4Q3pBSkJnTlZCQVlUQWxOSE1SSXdFQVlEVlFRSURBbFRhVzVuCllYQnZjbVV4RWpBUUJnTlZCQWNNQ1ZOcGJtZGhjRzl5WlRFaE1COEdBMVVFQ2d3WVZrMTNZWEpsSUZOcGJtZGgKY0c5eVpTQk1kR1FnVUhSbE1RNHdEQVlEVlFRTERBVnRZWEJpZFRFY01Cb0dBMVVFQXd3VFZrMVhZWEpsSUZSaApibnAxSUZaTVVDQkRRVEVrTUNJR0NTcUdTSWIzRFFFSkFSWVZlR2x1YzNSbGRtVnViRUIyYlhkaGNtVXVZMjl0Ck1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBd1NYTXV6eWI0T2E0QW9rUHNyU0kKT0duMy8zYUdnYklLYnhUcFo3cnhOT1VxdXRyTVBkT2ZrT3RhelhYWWF3VWIvMXZNUktsakl5bGxqdkJoL2p3RgpZSGtEZUkvNWtzNTVqbG1VNkxhNmNNZ2dhcEd0N1EwUjl1eC9IQmg3dEV6QXdXZUl0b0ZuTkdibTA2OGhnYWhkCktGYURVYld2UGVaajJzWmZJVnJmeHliYWJMaHNxbG1rcjNLNmZqVU90cngwRElxeXNnclhSRWMwa29aT2FSdHMKY3V0QmVia1QwM3BLdWg2OUxtWjlaWmVRL3h5LzM3ajhKRDF5M1lldjQ1disrdS83dkJXdzVDd3NaRE1jRkhzaQp3RDRTckpzSTRuS2ZISkxobTBxTjhoUndrMkpnTGkyWXVvRnYwaXkwa1hLelQvQUtuOWcxSVJVbnJlQU96Z0U4Cm8vWU1DUnBVWmlXcFgzOWpjTWZrQVZuUHRid2VRZGJEdlBoNS8rWVk4bVBqTUxOd3ZyRFJpWm1mNEsrMjlqWUMKaUxNNDB5N2xMS1k1U3R2K1c2dlNBZjlDZ0w3MlAwZU1BdTg1NHpMbmNUV1JMU2tKVnNldGZaMU5aQ1VwSWVPTAo3eW9TekwwVUVYVWZEWVdPQkpMY2dqN0tZZTZQbXVOMnhaNjY1OFF0dithTXBkaGN6b0FucmFIMGtkeHlUZFdlCmtidmUyNWFPRWNZT25LTithNmY4eFQyS1ByMHo2a0gxenRFdWVwQmZuSGNyNVlGaDNuYlo2b2RXN2xWbDZvN1AKVWZzTlROR2xsYkR5YzduTHhJV0E5eEJtRDBuMFdSM3hZVG1UY01UOVlpZ04zK0NZTzdYWTRydXRSRTZhR0x6eAo1WmtaQVNibHVUVjk4MWtxeWdHS3QrVUNBd0VBQWFPQ0FTMHdnZ0VwTUIwR0ExVWREZ1FXQkJTNDVncWdOdEVBCmlGVVZJdjhSckVrUGdMQkxIRENCN0FZRFZSMGpCSUhrTUlIaGdCUzQ1Z3FnTnRFQWlGVVZJdjhSckVrUGdMQkwKSEtHQnNxU0JyekNCckRFTE1Ba0dBMVVFQmhNQ1UwY3hFakFRQmdOVkJBZ01DVk5wYm1kaGNHOXlaVEVTTUJBRwpBMVVFQnd3SlUybHVaMkZ3YjNKbE1TRXdId1lEVlFRS0RCaFdUWGRoY21VZ1UybHVaMkZ3YjNKbElFeDBaQ0JRCmRHVXhEakFNQmdOVkJBc01CVzFoY0dKMU1Sd3dHZ1lEVlFRRERCTldUVmRoY21VZ1ZHRnVlblVnVmt4UUlFTkIKTVNRd0lnWUpLb1pJaHZjTkFRa0JGaFY0YVc1emRHVjJaVzVzUUhadGQyRnlaUzVqYjIyQ0ZBY2VFRFludTVBSQpibUoxMUlBSWdmazlFaFk4TUF3R0ExVWRFd1FGTUFNQkFmOHdDd1lEVlIwUEJBUURBZ0VHTUEwR0NTcUdTSWIzCkRRRUJDd1VBQTRJQ0FRQUN5Zjl0TTlLVGdXeFRJcENScHdBdUgrcXVhdEs4WTdIK1ZaRk5QSDlDTEFXS1cvT2QKeWVmNVk1VnQyRWJzQWRsZlpVNXVUNEFwNk5RbDJ0M0dZMlUzWUZSSXRSVlhJZkN2MDEyWmcxdzJDWVNYOVU3cwpGb0NIa3RWRm1GclFEdkoybWoyMWVKK0d2MzJURitXOXhMSU1pbWl4czN3NVNhbmhIaFNMaHE5cmw3RFlnYi9oClptUWk3eHR4dk9yOFEzQ3JzbFJqUkFQV0pZa2tNVzY5Z05nckV0M202ZHRzMnFOZ1MrYlorVHZ6aDBhblJRdEUKMG5LRHpsNGJTbWZ1NFYya0pwdi9FMkx3d2xDMVlyNXhSYTVCUjIrcjFRd3M1TnVLdDQ3dVI1OGZLOWdJT3M4YQp2WGsyNDBOQnF0Mk5MVzZ1MDVUTnR1YllNM1FmdHVnRmlCWXRCSjh5UklVUndCbjQ0N3FnNjJEdHAvSkpCLy9kCkxTbndrZkZxUW1sN1RDNENjY3V3QTlFQUxRTHNWRkhxcmpETXlwV0V4cFZ2ekNNTmlZa0x0d0JVVFpYT1hhTU8KRStwZUxjKzVwbWVjTkttSzVVZ2krc3hYNTBEeHZYMStFL0pQZ1BpY2xhamQ0Uk9aYU92Y0toT3g0RGJwQUlqeAoxRU9LQktvY3lWUnZLY1BVOERUUW55ZXFHSkNLdDRNNHhFcndTeGJLWllBZFl5cVFqeFYyZC8vcndrcGdOY1VZClRuWG9lQTdPVmhnZEJPYkdrQ0JtWUJYY0RBaXJZUis3SjExTFdFd296b0JYSXdTa2I5Z0p4N0hPcnEzY1BOU0cKeVlJd3RGQ285VllaY2xsd2xvdTBuTmR4QmhXTkl2b2w4MWhBd3ZzTmZPRG1uVUoyZVpLa0hCQi9iUT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
